In [1]:
include("Mosaic.jl")
include("Get_Focus.jl")
using Images
using FileIO
using Colors, Plots

In [2]:
using JLD2 
conf = load_object("Combined_Image.jld2")

20380×21380×3 Array{UInt16, 3}:
[:, :, 1] =
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x00

In [14]:
using Images

save("test.png",conf)

In [7]:
using JLD2 
data = load_object("/home/felix/rapid_storage_1/Microscope/focus_stacked/60814_40569.jld2")
using PyCall
np = pyimport("numpy")
data = np.asarray(data)
np.save("filename_python.npy",data)

In [8]:
plt = pyimport("matplotlib.pyplot")
fig = plt.figure(figsize=(16,16))
plt.imshow(data/np.amax(data))
plt.show()

In [5]:
data = load_object("/home/felix/rapid_storage_1/Microscope/focus/80400/82000/43500.jld2")
plt.imshow((data.-np.amin(data))./(np.amax(data)-np.amin(data)), cmap="hot")
plt.show()

In [6]:
np.std((data.-np.amin(data))./(np.amax(data)-np.amin(data)))

0.07075331332149581

In [1]:
using Random
len_y = Int((12)*0.5*3040)
len_z = Int((8)*0.5*4056)
test = zeros(Int16,3,len_z, len_y,3)
map!(vi->vi+rand(1:100),test,test)
tst = @view test[1, 1000:2000, 1000:2000 ,:]

1001×1001×3 view(::Array{Int16, 4}, 1, 1000:2000, 1000:2000, :) with eltype Int16:
[:, :, 1] =
 28  99  85  95  86  68  58   25   34  …  76  96  19  28  58  52   28  53  22
 81  19  39  13  85  73  99   98  100     78  98  24  93  47  31  100  13  19
 29  20  40  70  56  14  30   31   38     79  61  69  35   7  96   12  22  81
 60  67  27  93  86  47  24   67   90     87  54  17  16  26  66   37  40  21
 37  30  69  48  38   9   5   74   19     26  10  87  46   5  66   70  65  17
  6  28  86  35  38  69  54   15   65  …  43  21  84  13  65  69   80  71  48
 31  60  58  44  67   9  96   49   71     21  55  72  97  88  12   44  70  75
 41  34  50  57  99  88  51   35   11     71  81  69  23  49  10   49  94  87
 33  84  76  96  58  98  65   75   82     20  41  23  54   3  80   21  14  34
 88  82  34  17  91   2   3   89   65     60  63  99  51  23  28   85   4  20
 84  91  52  32   1  35  82   56   60  …  94  65  63  16  38  83   11  65   6
 30  37  30  46  99  22  70   10   67     94  7

In [13]:
bitarray = (sum(tst, dims=4) .== 10)
sum(bitarray), length(bitarray), size(bitarray), size(tst)

(29812, 3006003, (1001, 1001, 3), (1001, 1001, 3))

In [37]:
shape(tst)

1

In [19]:
tst[1:1, :,:,:]

1×1001×3×1 Array{Int16, 4}:
[:, :, 1, 1] =
 28  99  85  95  86  68  58  25  34  …  76  96  19  28  58  52  28  53  22

[:, :, 2, 1] =
 39  27  65  30  20  55  59  92  22  …  100  98  75  5  98  61  18  85  18

[:, :, 3, 1] =
 81  59  18  7  9  25  20  87  25  58  …  71  34  56  36  17  10  41  83  71

In [26]:
ls = []
ls2 = []
for i in 1:100
    push!(ls,i)
    push!(ls2,i)
end

In [27]:
(ls .== ls2[2])

100-element BitVector:
 0
 1
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [28]:
println(ls)

Any[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [29]:
time()

1.693920824037393e9

In [30]:
using JLD2
image_directory = "/media/felix/Drive/Images/img_6/"
save_path = "/home/felix/rapid_storage_1/Wasp/"

findat=load_object("$(save_path)FocusMosaicedImageMultipExp.jld2")

3×22308×22800×3 Array{UInt16, 4}:
[:, :, 1, 1] =
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000

[:, :, 2, 1] =
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000

[:, :, 3, 1] =
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000

;;; … 

[:, :, 22798, 1] =
 0x0000  0x0000  0x0000  0x0000  0x0000  …  0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000  0x0000
 0x0000  0x0000  0x0000  0x0000  0x0000     0x0000  0x0000  0x0000

In [36]:
files = readdir(image_directory)
    x_y_z_exp = [split(i, "_") for i in files]
    x_y_z = [[parse(Int, String(i[1])),parse(Int, String(i[2])), parse(Int, String(i[3]))] for i in x_y_z_exp]
    exp_ = unique([parse(Int, String(split(i[4], ".")[1])[4:end-3]) for i in x_y_z_exp])
    # Get x, y and z coordinates
    x = unique([i[1] for i in x_y_z])
    y = unique([i[2] for i in x_y_z])
    z = unique([i[3] for i in x_y_z])
    x = sort(x)
    y = sort(y)
    z = sort(z)
    exp_ = sort(exp_)

3-element Vector{Int64}:
  65536
 131072
 196608

In [37]:
using Images
for i in 1:3
    save("$(save_path)FocusedMosaicImage_$(exp_[i]).png",findat[i, : ,: ,:]) # exp, height, width, color
end

In [1]:
 # The LoG stil leaves gaps
 using JLD2
image_directory = "/media/felix/Drive/Images/img_6/"
save_path = "/home/felix/rapid_storage_1/Wasp/"

map_val=load_object("$(save_path)FocusMosaicedDepthmapVal.jld2")
map_=load_object("$(save_path)FocusMosaicedDepthmap.jld2")

22308×22800 Matrix{Int64}:
 -10  -10  -10  -10  -10  -10  -10  -10  …  -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10  …  -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10  …  -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -10     -10  -10  -10  -10  -10  -10  -10
 -10  -10  -10  -10  -10  -10  -10  -

In [4]:
map_val[map_val .> 0.01]

226190910-element Vector{Float64}:
 3867.3891622847905
 3657.2475629215064
 5674.454087178074
 4241.534924079559
 4724.337719465799
 5061.758736417818
 6302.410137121893
 6223.473877488318
 4261.688858990304
 3371.188245379024
 3129.1611980613525
 6096.251596784459
 4187.348478717246
    ⋮
 4402.315081740764
 3524.1197390685775
 2605.1897382342677
 3368.0093618431947
 5294.357449583862
 5322.836575428144
 3756.261408725113
 5098.9326639583305
 4487.000120130119
 3444.8829548989506
 4174.251903444791
 4936.026179001226

In [6]:
include("Get_Focus.jl")
# Copied from *single_loop.jl
function LoadDNGandRotate(path)
    rawpy = pyimport("rawpy") 
    np = pyimport("numpy") 
    im_1 = rawpy.imread(path)
    im_1=im_1.postprocess(demosaic_algorithm=rawpy.DemosaicAlgorithm(11),half_size=false, 
                                # 3color no brightness adjustment (default is false -> ie auto brightness)
                                four_color_rgb=false,no_auto_bright=true,
                                # If using dcb demosaicing
                                dcb_iterations=0, dcb_enhance=false, 
                                # Denoising
                                fbdd_noise_reduction=rawpy.FBDDNoiseReductionMode(0),noise_thr=nothing,
                                # Color
                                median_filter_passes=0,use_camera_wb=false,use_auto_wb=false, user_wb=nothing,
                                # sRGB output and output bits per sample : 8 is default
                                output_color=rawpy.ColorSpace(1),output_bps=16,
                                # Black levels for the sensor are predefined and cant be modified i think
                                user_flip=nothing, user_black=nothing,
                                # Adjust maximum threshholds only applied if value is nonzero default was 0.75
                                # https://www.libraw.org/docs/API-datastruct.html
                                user_sat=nothing, auto_bright_thr=nothing, adjust_maximum_thr=0, bright=1.0,
                                # Ignore default is Clip
                                highlight_mode=rawpy.HighlightMode(1), 
                                # Exp shift 1 is do nothing, nothing should achieve the same but to be sure, preserve 1 is full preservation
                                exp_shift=1, exp_preserve_highlights=1.0,
                                # V_out = gamma[0]*V_in^gamma 
                                gamma=(2.222, 4.5), chromatic_aberration=(1,1),bad_pixels_path=nothing
                                )
        return np.rot90(im_1)
end

LoadDNGandRotate (generic function with 1 method)

In [9]:
files = readdir(image_directory)

tst = abs.(ComputeFocusMap(LoadDNGandRotate("$(image_directory)$(files[100])") ,"l-star"))

4056×3040 Matrix{Float64}:
      1.43224e5       2.21051e5  …       2.33255e5       1.5026e5
 223721.0             3.37711e5          3.56717e5  234906.0
 184162.0             2.89162e5          3.06761e5       1.94882e5
      1.31484e5       2.21441e5          2.36143e5       1.41021e5
      1.12241e5       1.96265e5          2.10254e5       1.216e5
      1.11184e5       1.95489e5  …       2.11228e5       1.2186e5
 110892.0             1.95805e5          2.11066e5       1.21133e5
 111871.0             1.97913e5          2.08656e5       1.18231e5
      1.13344e5  200390.0                2.07922e5  116489.0
      1.13992e5       2.00746e5          2.10344e5  117916.0
      1.13025e5       1.98412e5  …  211949.0             1.19691e5
      1.12223e5       1.95936e5          2.10915e5       1.19332e5
      1.13078e5  196036.0                2.09604e5       1.18429e5
      ⋮                          ⋱                  
      1.21222e5  215996.0                1.72746e5   98665.2
      1.22